# Generated by Django 4.0.1 on 2022-01-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhw',
            name='subject',
            field=models.IntegerField(choices=[(1, 'ALGEBRA'), (2, 'RUSSIAN'), (3, 'HISTORY'), (4, 'ANATOMY'), (5, 'PHYSICS')], default=1, verbose_name='Subject'),
        ),
    ]
