# Generated by Django 4.0.1 on 2022-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_hw', '0002_alter_userhw_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhw',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='phone_number'),
        ),
    ]
